# Generated by Django 5.1.7 on 2025-03-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='title',
            new_name='job_title',
        ),
        migrations.AddField(
            model_name='resume',
            name='themeColor',
            field=models.CharField(default='#ff6666', max_length=200),
        ),
    ]
